#!/bin/bash

# b = -3
uv run --offline scripts/train_policy/train.py experiment_name=easy/her/mega_rb_dscnt_0_9_b_-3_eval_96_seed_1 algo=her_for_flycraft callback=sac_mega_replay_buffer callback.0.evaluate_nums_in_callback=6 env=flycraft_for_sac_mega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.b_used_in_omega=-3 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=flycraft train_steps=1e6 algo.seed=5 env.train_env.seed=2 env.evaluation_env.seed=8 env.callback_env.seed=9
uv run --offline scripts/train_policy/train.py experiment_name=easy/her/mega_rb_dscnt_0_9_b_-3_eval_96_seed_2 algo=her_for_flycraft callback=sac_mega_replay_buffer callback.0.evaluate_nums_in_callback=6 env=flycraft_for_sac_mega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.b_used_in_omega=-3 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=flycraft train_steps=1e6 algo.seed=14 env.train_env.seed=12 env.evaluation_env.seed=11 env.callback_env.seed=19
uv run --offline scripts/train_policy/train.py experiment_name=easy/her/mega_rb_dscnt_0_9_b_-3_eval_96_seed_3 algo=her_for_flycraft callback=sac_mega_replay_buffer callback.0.evaluate_nums_in_callback=6 env=flycraft_for_sac_mega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.b_used_in_omega=-3 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=flycraft train_steps=1e6 algo.seed=26 env.train_env.seed=21 env.evaluation_env.seed=23 env.callback_env.seed=27
uv run --offline scripts/train_policy/train.py experiment_name=easy/her/mega_rb_dscnt_0_9_b_-3_eval_96_seed_4 algo=her_for_flycraft callback=sac_mega_replay_buffer callback.0.evaluate_nums_in_callback=6 env=flycraft_for_sac_mega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.b_used_in_omega=-3 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=flycraft train_steps=1e6 algo.seed=34 env.train_env.seed=32 env.evaluation_env.seed=36 env.callback_env.seed=35
uv run --offline scripts/train_policy/train.py experiment_name=easy/her/mega_rb_dscnt_0_9_b_-3_eval_96_seed_5 algo=her_for_flycraft callback=sac_mega_replay_buffer callback.0.evaluate_nums_in_callback=6 env=flycraft_for_sac_mega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.b_used_in_omega=-3 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=flycraft train_steps=1e6 algo.seed=49 env.train_env.seed=43 env.evaluation_env.seed=48 env.callback_env.seed=42


# b = 0
uv run --offline scripts/train_policy/train.py experiment_name=easy/her/mega_rb_dscnt_0_9_b_0_eval_96_seed_1 algo=her_for_flycraft callback=sac_mega_replay_buffer callback.0.evaluate_nums_in_callback=6 env=flycraft_for_sac_mega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=flycraft train_steps=1e6 algo.seed=5 env.train_env.seed=2 env.evaluation_env.seed=8 env.callback_env.seed=9
uv run --offline scripts/train_policy/train.py experiment_name=easy/her/mega_rb_dscnt_0_9_b_0_eval_96_seed_2 algo=her_for_flycraft callback=sac_mega_replay_buffer callback.0.evaluate_nums_in_callback=6 env=flycraft_for_sac_mega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=flycraft train_steps=1e6 algo.seed=14 env.train_env.seed=12 env.evaluation_env.seed=11 env.callback_env.seed=19
uv run --offline scripts/train_policy/train.py experiment_name=easy/her/mega_rb_dscnt_0_9_b_0_eval_96_seed_3 algo=her_for_flycraft callback=sac_mega_replay_buffer callback.0.evaluate_nums_in_callback=6 env=flycraft_for_sac_mega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=flycraft train_steps=1e6 algo.seed=26 env.train_env.seed=21 env.evaluation_env.seed=23 env.callback_env.seed=27
uv run --offline scripts/train_policy/train.py experiment_name=easy/her/mega_rb_dscnt_0_9_b_0_eval_96_seed_4 algo=her_for_flycraft callback=sac_mega_replay_buffer callback.0.evaluate_nums_in_callback=6 env=flycraft_for_sac_mega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=flycraft train_steps=1e6 algo.seed=34 env.train_env.seed=32 env.evaluation_env.seed=36 env.callback_env.seed=35
uv run --offline scripts/train_policy/train.py experiment_name=easy/her/mega_rb_dscnt_0_9_b_0_eval_96_seed_5 algo=her_for_flycraft callback=sac_mega_replay_buffer callback.0.evaluate_nums_in_callback=6 env=flycraft_for_sac_mega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=flycraft train_steps=1e6 algo.seed=49 env.train_env.seed=43 env.evaluation_env.seed=48 env.callback_env.seed=42
