#!/bin/bash

## 根据replay buffer的数据估计p_ag，KL(u, p_ag)的初始值在[3,4]区间，训练50000步降到2以下
## 所以，将env.curriculum_kwargs.b_used_in_omega设为0，使KL降低到1以下时，才会100%在p_dg中采样目标

uv run --offline scripts/train_policy/train.py experiment_name=easy/sac/omega_rb_dscnt_0_9_b_0_eval_96_seed_1 algo=sac_for_flycraft callback=sac_omega_replay_buffer callback.0.evaluate_nums_in_callback=6 env=flycraft_for_sac_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_dg_method=mega env.curriculum_kwargs.b_used_in_omega=0 env.callback_env.num_process=16 evaluate=flycraft train_steps=1e6 algo.seed=5 env.train_env.seed=2 env.evaluation_env.seed=8 env.callback_env.seed=9
uv run --offline scripts/train_policy/train.py experiment_name=easy/sac/omega_rb_dscnt_0_9_b_0_eval_96_seed_2 algo=sac_for_flycraft callback=sac_omega_replay_buffer callback.0.evaluate_nums_in_callback=6 env=flycraft_for_sac_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_dg_method=mega env.curriculum_kwargs.b_used_in_omega=0 env.callback_env.num_process=16 evaluate=flycraft train_steps=1e6 algo.seed=14 env.train_env.seed=12 env.evaluation_env.seed=11 env.callback_env.seed=19
uv run --offline scripts/train_policy/train.py experiment_name=easy/sac/omega_rb_dscnt_0_9_b_0_eval_96_seed_3 algo=sac_for_flycraft callback=sac_omega_replay_buffer callback.0.evaluate_nums_in_callback=6 env=flycraft_for_sac_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_dg_method=mega env.curriculum_kwargs.b_used_in_omega=0 env.callback_env.num_process=16 evaluate=flycraft train_steps=1e6 algo.seed=26 env.train_env.seed=21 env.evaluation_env.seed=23 env.callback_env.seed=27
uv run --offline scripts/train_policy/train.py experiment_name=easy/sac/omega_rb_dscnt_0_9_b_0_eval_96_seed_4 algo=sac_for_flycraft callback=sac_omega_replay_buffer callback.0.evaluate_nums_in_callback=6 env=flycraft_for_sac_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_dg_method=mega env.curriculum_kwargs.b_used_in_omega=0 env.callback_env.num_process=16 evaluate=flycraft train_steps=1e6 algo.seed=34 env.train_env.seed=32 env.evaluation_env.seed=36 env.callback_env.seed=35
uv run --offline scripts/train_policy/train.py experiment_name=easy/sac/omega_rb_dscnt_0_9_b_0_eval_96_seed_5 algo=sac_for_flycraft callback=sac_omega_replay_buffer callback.0.evaluate_nums_in_callback=6 env=flycraft_for_sac_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_dg_method=mega env.curriculum_kwargs.b_used_in_omega=0 env.callback_env.num_process=16 evaluate=flycraft train_steps=1e6 algo.seed=49 env.train_env.seed=43 env.evaluation_env.seed=48 env.callback_env.seed=42
