#!/bin/bash

# lambda = 0.8

## generate desired goals randomly
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_8_b_0_n_100_eval_96_seed_1 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=random eval_cfg.eval_dg_num=1000 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_random seed=12
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_8_b_0_n_100_eval_96_seed_2 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=random eval_cfg.eval_dg_num=1000 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_random seed=25
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_8_b_0_n_100_eval_96_seed_3 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=random eval_cfg.eval_dg_num=1000 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_random seed=39
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_8_b_0_n_100_eval_96_seed_4 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=random eval_cfg.eval_dg_num=1000 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_random seed=47
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_8_b_0_n_100_eval_96_seed_5 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=random eval_cfg.eval_dg_num=1000 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_random seed=51

## generate desired goals by enumerating over fixed dg intervals
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_8_b_0_n_100_eval_96_seed_1 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=fixed eval_cfg.x_interval=0.02 eval_cfg.y_interval=0.02 eval_cfg.z_interval=0.02 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_fixed seed=15
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_8_b_0_n_100_eval_96_seed_2 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=fixed eval_cfg.x_interval=0.02 eval_cfg.y_interval=0.02 eval_cfg.z_interval=0.02 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_fixed seed=28
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_8_b_0_n_100_eval_96_seed_3 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=fixed eval_cfg.x_interval=0.02 eval_cfg.y_interval=0.02 eval_cfg.z_interval=0.02 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_fixed seed=33
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_8_b_0_n_100_eval_96_seed_4 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=fixed eval_cfg.x_interval=0.02 eval_cfg.y_interval=0.02 eval_cfg.z_interval=0.02 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_fixed seed=41
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_8_b_0_n_100_eval_96_seed_5 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=fixed eval_cfg.x_interval=0.02 eval_cfg.y_interval=0.02 eval_cfg.z_interval=0.02 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_fixed seed=56


# lambda = 0.95

## generate desired goals randomly
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_95_b_0_n_100_eval_96_seed_1 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=random eval_cfg.eval_dg_num=1000 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_random seed=12
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_95_b_0_n_100_eval_96_seed_2 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=random eval_cfg.eval_dg_num=1000 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_random seed=25
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_95_b_0_n_100_eval_96_seed_3 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=random eval_cfg.eval_dg_num=1000 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_random seed=39
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_95_b_0_n_100_eval_96_seed_4 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=random eval_cfg.eval_dg_num=1000 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_random seed=47
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_95_b_0_n_100_eval_96_seed_5 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=random eval_cfg.eval_dg_num=1000 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_random seed=51

## generate desired goals by enumerating over fixed dg intervals
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_95_b_0_n_100_eval_96_seed_1 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=fixed eval_cfg.x_interval=0.02 eval_cfg.y_interval=0.02 eval_cfg.z_interval=0.02 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_fixed seed=15
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_95_b_0_n_100_eval_96_seed_2 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=fixed eval_cfg.x_interval=0.02 eval_cfg.y_interval=0.02 eval_cfg.z_interval=0.02 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_fixed seed=28
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_95_b_0_n_100_eval_96_seed_3 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=fixed eval_cfg.x_interval=0.02 eval_cfg.y_interval=0.02 eval_cfg.z_interval=0.02 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_fixed seed=33
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_95_b_0_n_100_eval_96_seed_4 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=fixed eval_cfg.x_interval=0.02 eval_cfg.y_interval=0.02 eval_cfg.z_interval=0.02 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_fixed seed=41
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_95_b_0_n_100_eval_96_seed_5 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=fixed eval_cfg.x_interval=0.02 eval_cfg.y_interval=0.02 eval_cfg.z_interval=0.02 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_fixed seed=56


# lambda = 0.99

## generate desired goals randomly
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_99_b_0_n_100_eval_96_seed_1 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=random eval_cfg.eval_dg_num=1000 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_random seed=12
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_99_b_0_n_100_eval_96_seed_2 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=random eval_cfg.eval_dg_num=1000 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_random seed=25
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_99_b_0_n_100_eval_96_seed_3 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=random eval_cfg.eval_dg_num=1000 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_random seed=39
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_99_b_0_n_100_eval_96_seed_4 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=random eval_cfg.eval_dg_num=1000 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_random seed=47
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_99_b_0_n_100_eval_96_seed_5 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=random eval_cfg.eval_dg_num=1000 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_random seed=51

## generate desired goals by enumerating over fixed dg intervals
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_99_b_0_n_100_eval_96_seed_1 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=fixed eval_cfg.x_interval=0.02 eval_cfg.y_interval=0.02 eval_cfg.z_interval=0.02 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_fixed seed=15
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_99_b_0_n_100_eval_96_seed_2 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=fixed eval_cfg.x_interval=0.02 eval_cfg.y_interval=0.02 eval_cfg.z_interval=0.02 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_fixed seed=28
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_99_b_0_n_100_eval_96_seed_3 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=fixed eval_cfg.x_interval=0.02 eval_cfg.y_interval=0.02 eval_cfg.z_interval=0.02 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_fixed seed=33
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_99_b_0_n_100_eval_96_seed_4 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=fixed eval_cfg.x_interval=0.02 eval_cfg.y_interval=0.02 eval_cfg.z_interval=0.02 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_fixed seed=41
uv run --offline scripts/evaluate_ckpt/evaluate_my_push_slide.py algo_type=sac ckpt_dir=checkpoints/my_push/sac/omega_dscnt_0_99_b_0_n_100_eval_96_seed_5 env=my_push process_num=32 eval_cfg=my_push_random_dg_set eval_cfg.dg_gen_method=fixed eval_cfg.x_interval=0.02 eval_cfg.y_interval=0.02 eval_cfg.z_interval=0.02 gamma=0.95 eval_res_csv_file_suffix=eval_res_on_fixed seed=56
