#!/bin/bash

## Medium_Maze
uv run scripts/train.py experiment_name=sac/seed_1 algo=sac_for_my_antmaze callback=sac callback.0.success_key_in_info=success callback.0.eval_freq=100000 callback.1.save_checkpoint_every_n_timesteps=100000 env=my_antmaze_medium_for_sac evaluate=my_antmaze train_steps=1e7 algo.seed=5 env.train_env.seed=2 env.evaluation_env.seed=8 env.callback_env.seed=9
uv run scripts/train.py experiment_name=sac/seed_2 algo=sac_for_my_antmaze callback=sac callback.0.success_key_in_info=success callback.0.eval_freq=100000 callback.1.save_checkpoint_every_n_timesteps=100000 env=my_antmaze_medium_for_sac evaluate=my_antmaze train_steps=1e7 algo.seed=12 env.train_env.seed=15 env.evaluation_env.seed=14 env.callback_env.seed=17
uv run scripts/train.py experiment_name=sac/seed_3 algo=sac_for_my_antmaze callback=sac callback.0.success_key_in_info=success callback.0.eval_freq=100000 callback.1.save_checkpoint_every_n_timesteps=100000 env=my_antmaze_medium_for_sac evaluate=my_antmaze train_steps=1e7 algo.seed=26 env.train_env.seed=27 env.evaluation_env.seed=23 env.callback_env.seed=29
uv run scripts/train.py experiment_name=sac/seed_4 algo=sac_for_my_antmaze callback=sac callback.0.success_key_in_info=success callback.0.eval_freq=100000 callback.1.save_checkpoint_every_n_timesteps=100000 env=my_antmaze_medium_for_sac evaluate=my_antmaze train_steps=1e7 algo.seed=37 env.train_env.seed=31 env.evaluation_env.seed=36 env.callback_env.seed=33
uv run scripts/train.py experiment_name=sac/seed_5 algo=sac_for_my_antmaze callback=sac callback.0.success_key_in_info=success callback.0.eval_freq=100000 callback.1.save_checkpoint_every_n_timesteps=100000 env=my_antmaze_medium_for_sac evaluate=my_antmaze train_steps=1e7 algo.seed=43 env.train_env.seed=46 env.evaluation_env.seed=49 env.callback_env.seed=44

## U_Maze
uv run scripts/train.py experiment_name=sac/seed_1 algo=sac_for_my_antmaze callback=sac callback.0.success_key_in_info=success callback.0.eval_freq=100000 callback.1.save_checkpoint_every_n_timesteps=100000 env=my_antmaze_u_for_sac evaluate=my_antmaze train_steps=1e7 algo.seed=5 env.train_env.seed=2 env.evaluation_env.seed=8 env.callback_env.seed=9
uv run scripts/train.py experiment_name=sac/seed_2 algo=sac_for_my_antmaze callback=sac callback.0.success_key_in_info=success callback.0.eval_freq=100000 callback.1.save_checkpoint_every_n_timesteps=100000 env=my_antmaze_u_for_sac evaluate=my_antmaze train_steps=1e7 algo.seed=12 env.train_env.seed=15 env.evaluation_env.seed=14 env.callback_env.seed=17
uv run scripts/train.py experiment_name=sac/seed_3 algo=sac_for_my_antmaze callback=sac callback.0.success_key_in_info=success callback.0.eval_freq=100000 callback.1.save_checkpoint_every_n_timesteps=100000 env=my_antmaze_u_for_sac evaluate=my_antmaze train_steps=1e7 algo.seed=26 env.train_env.seed=27 env.evaluation_env.seed=23 env.callback_env.seed=29
uv run scripts/train.py experiment_name=sac/seed_4 algo=sac_for_my_antmaze callback=sac callback.0.success_key_in_info=success callback.0.eval_freq=100000 callback.1.save_checkpoint_every_n_timesteps=100000 env=my_antmaze_u_for_sac evaluate=my_antmaze train_steps=1e7 algo.seed=37 env.train_env.seed=31 env.evaluation_env.seed=36 env.callback_env.seed=33
uv run scripts/train.py experiment_name=sac/seed_5 algo=sac_for_my_antmaze callback=sac callback.0.success_key_in_info=success callback.0.eval_freq=100000 callback.1.save_checkpoint_every_n_timesteps=100000 env=my_antmaze_u_for_sac evaluate=my_antmaze train_steps=1e7 algo.seed=43 env.train_env.seed=46 env.evaluation_env.seed=49 env.callback_env.seed=44
