#!/bin/bash

## generate desired goals randomly
uv run --offline scripts/evaluate_ckpt/evaluate_my_reach.py algo_type=ppo ckpt_dir=checkpoints/myreach/easy/ppo/seed_1 env=my_reach_for_ppo process_num=64 eval_cfg=my_reach_random_dg_set eval_cfg.dg_gen_method=random eval_cfg.eval_dg_num=1000 eval_res_csv_file_suffix=eval_res_on_random seed=12
uv run --offline scripts/evaluate_ckpt/evaluate_my_reach.py algo_type=ppo ckpt_dir=checkpoints/myreach/easy/ppo/seed_2 env=my_reach_for_ppo process_num=64 eval_cfg=my_reach_random_dg_set eval_cfg.dg_gen_method=random eval_cfg.eval_dg_num=1000 eval_res_csv_file_suffix=eval_res_on_random seed=25
uv run --offline scripts/evaluate_ckpt/evaluate_my_reach.py algo_type=ppo ckpt_dir=checkpoints/myreach/easy/ppo/seed_3 env=my_reach_for_ppo process_num=64 eval_cfg=my_reach_random_dg_set eval_cfg.dg_gen_method=random eval_cfg.eval_dg_num=1000 eval_res_csv_file_suffix=eval_res_on_random seed=39
uv run --offline scripts/evaluate_ckpt/evaluate_my_reach.py algo_type=ppo ckpt_dir=checkpoints/myreach/easy/ppo/seed_4 env=my_reach_for_ppo process_num=64 eval_cfg=my_reach_random_dg_set eval_cfg.dg_gen_method=random eval_cfg.eval_dg_num=1000 eval_res_csv_file_suffix=eval_res_on_random seed=47
uv run --offline scripts/evaluate_ckpt/evaluate_my_reach.py algo_type=ppo ckpt_dir=checkpoints/myreach/easy/ppo/seed_5 env=my_reach_for_ppo process_num=64 eval_cfg=my_reach_random_dg_set eval_cfg.dg_gen_method=random eval_cfg.eval_dg_num=1000 eval_res_csv_file_suffix=eval_res_on_random seed=51

## generate desired goals by enumerating over fixed dg intervals
uv run --offline scripts/evaluate_ckpt/evaluate_my_reach.py algo_type=ppo ckpt_dir=checkpoints/myreach/easy/ppo/seed_1 env=my_reach_for_ppo process_num=64 eval_cfg=my_reach_random_dg_set eval_cfg.dg_gen_method=fixed eval_cfg.x_interval=0.02 eval_cfg.y_interval=0.02 eval_cfg.z_interval=0.02 eval_res_csv_file_suffix=eval_res_on_fixed seed=15
uv run --offline scripts/evaluate_ckpt/evaluate_my_reach.py algo_type=ppo ckpt_dir=checkpoints/myreach/easy/ppo/seed_2 env=my_reach_for_ppo process_num=64 eval_cfg=my_reach_random_dg_set eval_cfg.dg_gen_method=fixed eval_cfg.x_interval=0.02 eval_cfg.y_interval=0.02 eval_cfg.z_interval=0.02 eval_res_csv_file_suffix=eval_res_on_fixed seed=28
uv run --offline scripts/evaluate_ckpt/evaluate_my_reach.py algo_type=ppo ckpt_dir=checkpoints/myreach/easy/ppo/seed_3 env=my_reach_for_ppo process_num=64 eval_cfg=my_reach_random_dg_set eval_cfg.dg_gen_method=fixed eval_cfg.x_interval=0.02 eval_cfg.y_interval=0.02 eval_cfg.z_interval=0.02 eval_res_csv_file_suffix=eval_res_on_fixed seed=33
uv run --offline scripts/evaluate_ckpt/evaluate_my_reach.py algo_type=ppo ckpt_dir=checkpoints/myreach/easy/ppo/seed_4 env=my_reach_for_ppo process_num=64 eval_cfg=my_reach_random_dg_set eval_cfg.dg_gen_method=fixed eval_cfg.x_interval=0.02 eval_cfg.y_interval=0.02 eval_cfg.z_interval=0.02 eval_res_csv_file_suffix=eval_res_on_fixed seed=41
uv run --offline scripts/evaluate_ckpt/evaluate_my_reach.py algo_type=ppo ckpt_dir=checkpoints/myreach/easy/ppo/seed_5 env=my_reach_for_ppo process_num=64 eval_cfg=my_reach_random_dg_set eval_cfg.dg_gen_method=fixed eval_cfg.x_interval=0.02 eval_cfg.y_interval=0.02 eval_cfg.z_interval=0.02 eval_res_csv_file_suffix=eval_res_on_fixed seed=56
