#!/bin/bash

# discounted_factor = 0.9, b = 0, n = 100, eval_num = 96
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_100_eval_96_seed_1 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=5 env.train_env.seed=2 env.evaluation_env.seed=8 env.callback_env.seed=9
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_100_eval_96_seed_2 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=12 env.train_env.seed=15 env.evaluation_env.seed=14 env.callback_env.seed=17
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_100_eval_96_seed_3 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=26 env.train_env.seed=27 env.evaluation_env.seed=23 env.callback_env.seed=29
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_100_eval_96_seed_4 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=37 env.train_env.seed=31 env.evaluation_env.seed=36 env.callback_env.seed=33
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_100_eval_96_seed_5 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=43 env.train_env.seed=46 env.evaluation_env.seed=49 env.callback_env.seed=44


# discounted_factor = 0.8, b = 0, n = 100, eval_num = 96
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_8_b_0_n_100_eval_96_seed_1 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.8 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=5 env.train_env.seed=2 env.evaluation_env.seed=8 env.callback_env.seed=9
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_8_b_0_n_100_eval_96_seed_2 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.8 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=12 env.train_env.seed=15 env.evaluation_env.seed=14 env.callback_env.seed=17
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_8_b_0_n_100_eval_96_seed_3 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.8 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=26 env.train_env.seed=27 env.evaluation_env.seed=23 env.callback_env.seed=29
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_8_b_0_n_100_eval_96_seed_4 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.8 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=37 env.train_env.seed=31 env.evaluation_env.seed=36 env.callback_env.seed=33
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_8_b_0_n_100_eval_96_seed_5 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.8 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=43 env.train_env.seed=46 env.evaluation_env.seed=49 env.callback_env.seed=44


# discounted_factor = 0.95, b = 0, n = 100, eval_num = 96
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_95_b_0_n_100_eval_96_seed_1 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.95 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=5 env.train_env.seed=2 env.evaluation_env.seed=8 env.callback_env.seed=9
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_95_b_0_n_100_eval_96_seed_2 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.95 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=12 env.train_env.seed=15 env.evaluation_env.seed=14 env.callback_env.seed=17
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_95_b_0_n_100_eval_96_seed_3 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.95 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=26 env.train_env.seed=27 env.evaluation_env.seed=23 env.callback_env.seed=29
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_95_b_0_n_100_eval_96_seed_4 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.95 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=37 env.train_env.seed=31 env.evaluation_env.seed=36 env.callback_env.seed=33
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_95_b_0_n_100_eval_96_seed_5 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.95 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=43 env.train_env.seed=46 env.evaluation_env.seed=49 env.callback_env.seed=44


# discounted_factor = 0.9, b = -1, n = 100, eval_num = 96
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_-1_n_100_eval_96_seed_1 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=-1 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=5 env.train_env.seed=2 env.evaluation_env.seed=8 env.callback_env.seed=9
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_-1_n_100_eval_96_seed_2 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=-1 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=12 env.train_env.seed=15 env.evaluation_env.seed=14 env.callback_env.seed=17
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_-1_n_100_eval_96_seed_3 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=-1 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=26 env.train_env.seed=27 env.evaluation_env.seed=23 env.callback_env.seed=29
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_-1_n_100_eval_96_seed_4 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=-1 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=37 env.train_env.seed=31 env.evaluation_env.seed=36 env.callback_env.seed=33
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_-1_n_100_eval_96_seed_5 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=-1 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=43 env.train_env.seed=46 env.evaluation_env.seed=49 env.callback_env.seed=44


# discounted_factor = 0.9, b = -2, n = 100, eval_num = 96
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_-2_n_100_eval_96_seed_1 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=-2 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=5 env.train_env.seed=2 env.evaluation_env.seed=8 env.callback_env.seed=9
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_-2_n_100_eval_96_seed_2 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=-2 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=12 env.train_env.seed=15 env.evaluation_env.seed=14 env.callback_env.seed=17
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_-2_n_100_eval_96_seed_3 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=-2 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=26 env.train_env.seed=27 env.evaluation_env.seed=23 env.callback_env.seed=29
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_-2_n_100_eval_96_seed_4 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=-2 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=37 env.train_env.seed=31 env.evaluation_env.seed=36 env.callback_env.seed=33
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_-2_n_100_eval_96_seed_5 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=-2 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=43 env.train_env.seed=46 env.evaluation_env.seed=49 env.callback_env.seed=44


# discounted_factor = 0.9, b = 0, n = 10, eval_num = 96
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_10_eval_96_seed_1 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=10 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=5 env.train_env.seed=2 env.evaluation_env.seed=8 env.callback_env.seed=9
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_10_eval_96_seed_2 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=10 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=12 env.train_env.seed=15 env.evaluation_env.seed=14 env.callback_env.seed=17
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_10_eval_96_seed_3 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=10 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=26 env.train_env.seed=27 env.evaluation_env.seed=23 env.callback_env.seed=29
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_10_eval_96_seed_4 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=10 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=37 env.train_env.seed=31 env.evaluation_env.seed=36 env.callback_env.seed=33
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_10_eval_96_seed_5 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=10 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=43 env.train_env.seed=46 env.evaluation_env.seed=49 env.callback_env.seed=44


# discounted_factor = 0.9, b = 0, n = 20, eval_num = 96
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_20_eval_96_seed_1 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=20 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=5 env.train_env.seed=2 env.evaluation_env.seed=8 env.callback_env.seed=9
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_20_eval_96_seed_2 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=20 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=12 env.train_env.seed=15 env.evaluation_env.seed=14 env.callback_env.seed=17
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_20_eval_96_seed_3 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=20 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=26 env.train_env.seed=27 env.evaluation_env.seed=23 env.callback_env.seed=29
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_20_eval_96_seed_4 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=20 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=37 env.train_env.seed=31 env.evaluation_env.seed=36 env.callback_env.seed=33
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_20_eval_96_seed_5 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=6 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=20 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=43 env.train_env.seed=46 env.evaluation_env.seed=49 env.callback_env.seed=44


# discounted_factor = 0.9, b = 0, n = 100, eval_num = 32
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_100_eval_32_seed_1 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=2 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=5 env.train_env.seed=2 env.evaluation_env.seed=8 env.callback_env.seed=9
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_100_eval_32_seed_2 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=2 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=12 env.train_env.seed=15 env.evaluation_env.seed=14 env.callback_env.seed=17
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_100_eval_32_seed_3 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=2 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=26 env.train_env.seed=27 env.evaluation_env.seed=23 env.callback_env.seed=29
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_100_eval_32_seed_4 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=2 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=37 env.train_env.seed=31 env.evaluation_env.seed=36 env.callback_env.seed=33
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_100_eval_32_seed_5 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=2 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=43 env.train_env.seed=46 env.evaluation_env.seed=49 env.callback_env.seed=44


# discounted_factor = 0.9, b = 0, n = 100, eval_num = 288
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_100_eval_288_seed_1 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=18 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=5 env.train_env.seed=2 env.evaluation_env.seed=8 env.callback_env.seed=9
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_100_eval_288_seed_2 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=18 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=12 env.train_env.seed=15 env.evaluation_env.seed=14 env.callback_env.seed=17
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_100_eval_288_seed_3 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=18 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=26 env.train_env.seed=27 env.evaluation_env.seed=23 env.callback_env.seed=29
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_100_eval_288_seed_4 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=18 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=37 env.train_env.seed=31 env.evaluation_env.seed=36 env.callback_env.seed=33
uv run --offline scripts/train_policy/train.py experiment_name=sac/omega_dscnt_0_9_b_0_n_100_eval_288_seed_5 algo=sac_for_my_push callback=sac_omega callback.0.evaluate_nums_in_callback=18 env=my_push_omega env.curriculum_kwargs.kde_data_discounted_factor=0.9 env.curriculum_kwargs.sample_n=100 env.curriculum_kwargs.b_used_in_omega=0 env.curriculum_kwargs.sample_dg_method=mega env.callback_env.num_process=16 evaluate=my_push train_steps=1e6 algo.seed=43 env.train_env.seed=46 env.evaluation_env.seed=49 env.callback_env.seed=44
